const dummyData = [
  {
    id: 1,
    name: "Smartphone X",
    company: "TechCorp",
    category: "phone",
    price: 699,
    rating: 4.5,
    discount: 10,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 2,
    name: "Wireless Earphones",
    company: "SoundWave",
    category: "earphone",
    price: 149,
    rating: 4.0,
    discount: 15,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 3,
    name: "4K Ultra HD TV",
    company: "VisionTech",
    category: "tv",
    price: 999,
    rating: 4.8,
    discount: 5,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 4,
    name: "Gaming Laptop",
    company: "GameMaster",
    category: "laptop PC",
    price: 1299,
    rating: 4.6,
    discount: 20,
    availability: false,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 5,
    name: "Tablet Pro",
    company: "FitTech",
    category: "tablet",
    price: 299,
    rating: 4.2,
    discount: 10,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    company: "AudioLux",
    category: "speaker",
    price: 79,
    rating: 4.3,
    discount: 25,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 7,
    name: "Gaming Mouse",
    company: "GameTech",
    category: "mouse",
    price: 49,
    rating: 4.7,
    discount: 30,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 8,
    name: "Portable Charger",
    company: "PowerPlus",
    category: "charger",
    price: 39,
    rating: 4.0,
    discount: 5,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 9,
    name: "Gaming Keyboard",
    company: "GameTech",
    category: "keyboard",
    price: 89,
    rating: 4.6,
    discount: 15,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 10,
    name: "HDMI Cable",
    company: "Cables R Us",
    category: "accessories",
    price: 19,
    rating: 4.1,
    discount: 10,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 11,
    name: "Bluetooth Headset",
    company: "AudioWave",
    category: "headset",
    price: 99,
    rating: 4.4,
    discount: 20,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 12,
    name: "USB-C Pendrive",
    company: "StoragePro",
    category: "pendrive",
    price: 29,
    rating: 4.7,
    discount: 15,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 13,
    name: "Smart TV Remote",
    company: "VisionTech",
    category: "remote",
    price: 15,
    rating: 4.0,
    discount: 0,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 14,
    name: "Wireless Charger",
    company: "ChargeFast",
    category: "charger",
    price: 49,
    rating: 4.3,
    discount: 10,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 15,
    name: "Bluetooth Mouse",
    company: "CoolTech",
    category: "mouse",
    price: 35,
    rating: 4.5,
    discount: 5,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 16,
    name: "Gaming Headset",
    company: "AudioMasters",
    category: "headset",
    price: 89,
    rating: 4.8,
    discount: 15,
    availability: false,
    image: "https://via.placeholder.com/200",
  },
];

export default dummyData;
