const dummyData = [
  {
    id: 1,
    name: "Smartphone X",
    company: "TechCorp",
    category: "Electronics",
    price: 699,
    rating: 4.5,
    discount: 10,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 2,
    name: "Wireless Headphones",
    company: "SoundWave",
    category: "Audio",
    price: 149,
    rating: 4.0,
    discount: 15,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 3,
    name: "4K Ultra HD TV",
    company: "VisionTech",
    category: "Electronics",
    price: 999,
    rating: 4.8,
    discount: 5,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 4,
    name: "Gaming Laptop",
    company: "GameMaster",
    category: "Computers",
    price: 1299,
    rating: 4.6,
    discount: 20,
    availability: false,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 5,
    name: "Smartwatch Pro",
    company: "FitTech",
    category: "Wearables",
    price: 299,
    rating: 4.2,
    discount: 10,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    company: "AudioLux",
    category: "Audio",
    price: 79,
    rating: 4.3,
    discount: 25,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 7,
    name: "Gaming Mouse",
    company: "GameTech",
    category: "Accessories",
    price: 49,
    rating: 4.7,
    discount: 30,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
  {
    id: 8,
    name: "Electric Kettle",
    company: "HomeAppliance",
    category: "Kitchen",
    price: 39,
    rating: 4.0,
    discount: 5,
    availability: true,
    image: "https://via.placeholder.com/200",
  },
];

export default dummyData;
